name: Check PIO buildability on PR into main branch

on:
    pull_request:
        branches:
            - main

jobs:
    pio-build:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}

        steps:
            - uses: actions/checkout@v4
            - name: Update OTA_VERSION
              run: |
                echo "PLATFORMIO_BUILD_FLAGS=-DOTA_VERSION=\\\"cicd_build\\\" -DOTA_BUILT_ON_GITHUB" >> $GITHUB_ENV

            - name: Set up PlatformIO
              run: |
                  sudo apt-get install -y python3-pip
                  pip3 install platformio
              shell: bash

            - name: Build Firmware
              run: pio run -e esp32

            - name: Check Build Status
              run: exit $?